In [1]:
 !pip install datasets

In [2]:
from datasets import load_dataset

In [3]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers", split='train')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [4]:
print (dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})


In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame(dataset)
print(df)

        Unnamed: 0.1  Unnamed: 0  \
0                  0         0.0   
1                  1         1.0   
2                  2         2.0   
3                  3         3.0   
4                  4         4.0   
...              ...         ...   
117587          4995         NaN   
117588          4996         NaN   
117589          4997         NaN   
117590          4998         NaN   
117591          4999         NaN   

                                                    title  \
0                   Learning from compressed observations   
1       Sensor Networks with Random Links: Topology De...   
2       The on-line shortest path problem under partia...   
3         A neural network approach to ordinal regression   
4        Parametric Learning and Monte Carlo Optimization   
...                                                   ...   
117587  Detecting COVID-19 Conspiracy Theories with Tr...   
117588  Fair Feature Subset Selection using Multiobjec...   
117589  A Simple D

In [7]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [8]:
df = df[['title','abstract']].copy()

In [9]:
df


,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [10]:
df.shape

(117592, 2)

In [11]:
df = df.head(15000)

In [12]:
df.shape

(15000, 2)

In [13]:
df.isnull().sum()

,0
title,0
abstract,0


In [14]:
df["paper_text"] = df['title']+" "+df['abstract']

/tmp/ipykernel_58924/2181642906.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"] = df['title']+" "+df['abstract']


In [15]:
df[['paper_text']].head()

,paper_text
0,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimizati...


In [16]:
type(df[['paper_text']])

pandas.core.frame.DataFrame

In [17]:
print(df['paper_text'].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regress

In [18]:
from sentence_transformers import SentenceTransformer

In [19]:
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

In [20]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>


In [21]:
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_58924/2190359946.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
/tmp/ipykernel_58924/2190359946.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()


In [22]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regres

In [23]:
embedding = model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)


In [24]:
embedding[:56]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474,
        0.05692544,  0.0201578 ,  0.0258311 ,  0.0321703 ,  0.10513764,
       -0.09676763,  0.02700802, -0.0234509 , -0.04549678, -0.01013699,
       -0.01794855, -0.04814427,  0.01077652, -0.03759069,  0.01943481,
        0.03715189,  0.02967844,  0.04330941,  0.04373213,  0.03704866,
       -0.00182594,  0.00455183, -0.00799067,  0.03037368, -0.014378  ,
        0.03795147,  0.0595916 , -0.02583356, -0.06521576,  0.05900268,
       -0.02107134,  0.07359422, -0.05720106,  0.00294061,  0.00767515,
       -0.0333416 ], dtype=float32)

In [25]:
sample_embedding = model.encode(df["paper_text"].head(5).to_list())

In [26]:
print(sample_embedding.shape)

(5, 384)


In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
similarity = cosine_similarity(sample_embedding[0].reshape(1,-1), sample_embedding[1].reshape(1,-1))
print(similarity)

[[0.36625272]]


In [29]:
for i in range (1,5):
  similarity = cosine_similarity(sample_embedding[0].reshape(1,-1), sample_embedding[i].reshape(1,-1))
  print(similarity)

[[0.36625272]]
[[0.33522844]]
[[0.15505108]]
[[0.37421533]]


Generating Full embedding for whole 15000


In [30]:
import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings")
    embedding = np.load("paper_embeddings.npy")
else:
    print("Generating embeddings")
    embedding = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save("paper_embeddings.npy", embedding)
    print("Embeddings saved successfully!")

Loading saved embeddings


In [31]:
print(embedding.shape)
print(type(embedding))

(15000, 384)
<class 'numpy.ndarray'>


In [32]:
embedding.dtype

dtype('float32')

In [33]:
!pip install faiss-cpu

In [34]:
import faiss

In [35]:
if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index")
    index = faiss.read_index("paper_faiss.index")
else:
    print("Creating new FAISS index")
    faiss.normalize_L2(embedding)
    index = faiss.IndexFlatIP(384)
    index.add(embedding)

Creating new FAISS index


In [36]:
print(index.ntotal)

15000


In [37]:
query = "deep learning for medical image analysis"
query_embedding=model.encode([query])
query_embedding.shape

(1, 384)

In [38]:
faiss.normalize_L2(query_embedding)

In [39]:
D,I = index.search(query_embedding , 5)
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]


In [40]:
print(df.iloc[10466]["title"])

A Perspective on Deep Imaging


In [41]:
print(df.iloc[10466]["abstract"])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.



In [42]:
print(df.iloc[11873]["title"])

Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection


In [43]:
def search_paper(query , k=5):
   query_embedding= model.encode([query])
   faiss.normalize_L2(query_embedding)
   D,I = index.search(query_embedding , k)
   return D,I

In [44]:
D,I = search_paper("deep learning for medical image analysis")
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]


In [45]:
def search_paper(query , k=5):
   query_embedding= model.encode([query])
   faiss.normalize_L2(query_embedding)
   D,I = index.search(query_embedding , k)
   return D,I

In [46]:
def search_paper(query , k=5):
   query_embedding= model.encode([query])
   faiss.normalize_L2(query_embedding)
   D,I = index.search(query_embedding,k)
   for score,idx in zip(D[0], I[0]):
      print("Similarity score", score)
      print("Title",df.iloc[idx]["title"])
      print("Abstract", df.iloc[idx]["abstract"][:500])

In [47]:
search_paper("deep learning for medical image analysis")

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Abstract   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a 

In [48]:
!pip install transformers==4.46.3

In [49]:
from  transformers import  pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

In [50]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

In [51]:
summary=summarizer(df.iloc[10466]["abstract"],max_length=120,min_length=40)
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]


In [52]:
type(summary)

list

In [53]:
type(summary[0])

dict

In [54]:
summary[0]["summary_text"]

'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'

In [55]:
for score,idx in zip(D[0], I[0]):
  print("Similarity score", score)
  print("Title",df.iloc[idx]["title"])
  print("Abstract", df.iloc[idx]["abstract"][:500])

  summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40)
  print(summary)
  print(summary[0]["summary_text"])



Similarity score 0.6807244
Title A Perspective on Deep Imaging
Abstract   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or mac

Keybert

In [56]:
def search_and_summarize(query , k=5):
   query_embedding= model.encode([query])
   faiss.normalize_L2(query_embedding)
   D,I = index.search(query_embedding,k)
   for score,idx in zip(D[0], I[0]):
      print("Similarity score", score)
      print("Title",df.iloc[idx]["title"])
      print("Abstract", df.iloc[idx]["abstract"][:500])
      summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40 , do_sample = False)
      print(summary)
      print(summary[0]["summary_text"])

In [58]:
pip install keybert==0.8.5

In [59]:
from keybert import KeyBERT

In [60]:
kw_model = KeyBERT(model)

In [61]:
type(kw_model)

keybert._model.KeyBERT

In [62]:
text = df.iloc[10466]["abstract"]
keyword = kw_model.extract_keywords(text)
print(keyword)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]


In [63]:
print(type(keyword))
print(type(keyword[0]))

<class 'list'>
<class 'tuple'>


In [64]:
keywords = kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 3), stop_words="english")

In [65]:
print(keywords)

[('tomographic imaging deep', 0.6704), ('imaging deep learning', 0.6543), ('learning medical imaging', 0.6041), ('imaging deep', 0.5919), ('medical imaging', 0.5281)]


In [66]:
def search_and_summarize(query, k=5):

    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):

        title = df.iloc[idx]["title"]
        abstract = df.iloc[idx]["abstract"]

        print("=" * 70)
        print("Similarity Score :", round(float(score), 4))
        print("Title :", title)


        topic, confidence = classify_topic(abstract)
        print("Predicted Topic :", topic)
        print("Confidence :", round(confidence * 100, 2), "%")
        print()


        print("Abstract :")
        print(abstract[:500])
        print()


        entities = extract_entities(abstract)

        print("Named Entities:")
        if len(entities) == 0:
            print("No entities found.")
        else:
            for entity, label in entities[:10]:
                print(f"- {entity} ({label})")

        print()
        summary = summarizer(
            abstract,
            max_length=120,
            min_length=40,
            do_sample=False
        )

        print("Summary:")
        print(summary[0]["summary_text"])
        print()
        score = textstat.flesch_reading_ease(abstract)

        print("Readability Score:", round(score,2))
        print()

        keywords = kw_model.extract_keywords(
            abstract,
            keyphrase_ngram_range=(1, 3),
            stop_words="english"
        )

        print("Keywords:")
        for key, score_kw in keywords:
            print("-", key)

        print("\n" + "=" * 70 + "\n")

In [67]:
!pip install textstat
import textstat

print("TextStat Loaded Successfully")

TextStat Loaded Successfully


In [68]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

labels = [
    "Natural Language Processing",
    "Computer Vision",
    "Machine Learning",
    "Deep Learning",
    "Healthcare AI",
    "Robotics",
    "Cybersecurity",
    "Data Mining",
    "Reinforcement Learning"
]

def classify_topic(text):
    result = classifier(text, candidate_labels=labels)
    return result["labels"][0], result["scores"][0]

print("Topic Classification Loaded")

Topic Classification Loaded


In [69]:
import spacy

nlp = spacy.load("en_core_web_sm")

def extract_entities(text):
    doc = nlp(text)
    return [(ent.text, ent.label_) for ent in doc.ents]

print("NER Loaded Successfully")

NER Loaded Successfully


In [70]:
text = """
Deep learning models are widely used for detecting lung cancer from medical images using convolutional neural networks.
"""

topic, confidence = classify_topic(text)

print("Predicted Topic:", topic)
print("Confidence:", round(confidence * 100, 2), "%")

Predicted Topic: Deep Learning
Confidence: 53.23 %


In [71]:
text = """
Researchers from Stanford University developed an AI model using TensorFlow to analyze MRI scans at Google Health.
"""

entities = extract_entities(text)

print("Named Entities:")
for entity, label in entities:
    print(f"{entity} --> {label}")

Named Entities:
Stanford University --> ORG
AI --> GPE
TensorFlow --> ORG
Google Health --> ORG


In [72]:
!pip install textstat

In [73]:
search_and_summarize("Deep learning in medical imaging", k=5)

Similarity Score : 0.7355
Title : A Perspective on Deep Imaging
Predicted Topic : Machine Learning
Confidence : 60.56 %

Abstract :
  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

Named Entities:
No entities found.

Summary:
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in cli